language: csharp
solution: BencodeNET.sln
install:
  - nuget restore BencodeNET.sln
  - nuget install xunit.runner.console -Version 2.1.0-rc1-build3168 -OutputDirectory xunit
script:
  - xbuild /p:Configuration=Release BencodeNET.sln
  - mono ./xunit/xunit.runner.console.2.1.0-rc1-build3168/tools/xunit.console.exe ./BencodeNET.Tests/bin/Release/BencodeNET.Tests.dll
  
  
