language: csharp
solution: BencodeNET.sln
install:
  - nuget restore BencodeNET.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory xunit
script:
  - xbuild /p:Configuration=Release BencodeNET.sln
  - mono ./xunit/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./BencodeNET.Tests/bin/Release/BencodeNET.Tests.dll
  
  
